version: '3.9'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - uber-popug
    ports:
      - 8081:8081

  task:
    build:
      context: ./task
      dockerfile: Dockerfile
    networks:
      - uber-popug
    ports:
      - 8082:8082

  billing:
    build:
      context: ./billing
      dockerfile: Dockerfile
    networks:
      - uber-popug
    ports:
      - 8083:8083

  analitycs:
    build:
      context: ./analitycs
      dockerfile: Dockerfile
    networks:
      - uber-popug
    ports:
      - 8084:8084

networks:
  uber-popug:
