# https://taskfile.dev/#/installation
version: '3'

silent: true

tasks:
  default:
    task -l

  0:
    desc: Stop docker-compose
    cmds:
      - docker-compose down

  1:
    desc: Run docker-compose
    cmds:
      - docker-compose up --build
